// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hrmSolution.Data.EF;

namespace hrmSolution.Data.Migrations
{
    [DbContext(typeof(HrmDbContext))]
    [Migration("20210801160107_AddColumnAvatar")]
    partial class AddColumnAvatar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("hrmSolution.Data.Entities.Tbl_ChiTietQuyenTheoManHinh", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("C_IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2)
                        .HasColumnName("c_IsDeleted");

                    b.Property<DateTime>("C_NgayTao")
                        .HasColumnType("datetime")
                        .HasColumnName("c_NgayTao");

                    b.Property<int>("C_TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("c_TrangThai");

                    b.Property<Guid>("Fk_DanhMucChucNang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Fk_DanhMucManHinh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Fk_DanhMucTenQuyen")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Fk_DanhMucChucNang");

                    b.HasIndex("Fk_DanhMucManHinh");

                    b.HasIndex("Fk_DanhMucTenQuyen");

                    b.ToTable("Tbl_ChiTietQuyenTheoManHinh");
                });

            modelBuilder.Entity("hrmSolution.Data.Entities.Tbl_DanhMucChucNang", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("C_Code")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("c_Code");

                    b.Property<int>("C_IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2)
                        .HasColumnName("c_IsDeleted");

                    b.Property<DateTime>("C_NgayTao")
                        .HasColumnType("datetime")
                        .HasColumnName("c_NgayTao");

                    b.Property<string>("C_TenChucNang")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_TenChucNang");

                    b.Property<int>("C_TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("c_TrangThai");

                    b.HasKey("Id");

                    b.HasIndex("C_Code")
                        .IsUnique();

                    b.ToTable("Tbl_DanhMucChucNang");
                });

            modelBuilder.Entity("hrmSolution.Data.Entities.Tbl_DanhMucManHinh", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("C_Code")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("c_Code");

                    b.Property<int>("C_IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2)
                        .HasColumnName("c_IsDeleted");

                    b.Property<DateTime>("C_NgayTao")
                        .HasColumnType("datetime")
                        .HasColumnName("c_NgayTao");

                    b.Property<string>("C_TenManHinh")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_TenManHinh");

                    b.Property<int>("C_TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("c_TrangThai");

                    b.HasKey("Id");

                    b.HasIndex("C_Code")
                        .IsUnique();

                    b.ToTable("Tbl_DanhMucManHinh");
                });

            modelBuilder.Entity("hrmSolution.Data.Entities.Tbl_DanhMucTenQuyen", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("C_Code")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("c_Code");

                    b.Property<int>("C_IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2)
                        .HasColumnName("c_IsDeleted");

                    b.Property<DateTime>("C_NgayTao")
                        .HasColumnType("datetime")
                        .HasColumnName("c_NgayTao");

                    b.Property<string>("C_TenQuyen")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_TenQuyen");

                    b.Property<int>("C_TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("c_TrangThai");

                    b.HasKey("Id");

                    b.HasIndex("C_Code")
                        .IsUnique();

                    b.ToTable("Tbl_DanhMucTenQuyen");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ef507d6-48ff-419d-bffa-07291275379e"),
                            C_Code = "ROLE001",
                            C_IsDeleted = 2,
                            C_NgayTao = new DateTime(2021, 8, 1, 23, 1, 6, 933, DateTimeKind.Local).AddTicks(5270),
                            C_TenQuyen = "Admin",
                            C_TrangThai = 2
                        });
                });

            modelBuilder.Entity("hrmSolution.Data.Entities.Tbl_NguoiDung", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("C_Avatar")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("c_Avatar");

                    b.Property<string>("C_Code")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)")
                        .HasColumnName("c_Code");

                    b.Property<string>("C_Email")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("c_Email");

                    b.Property<string>("C_HoVaTen")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_HoVaTen");

                    b.Property<int>("C_IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2)
                        .HasColumnName("c_IsDeleted");

                    b.Property<string>("C_MatKhau")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("c_MatKhau");

                    b.Property<DateTime>("C_NgayTao")
                        .HasColumnType("datetime")
                        .HasColumnName("c_NgayTao");

                    b.Property<string>("C_SoDienThoai")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("c_SoDienThoai");

                    b.Property<int>("C_TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("c_TrangThai");

                    b.Property<Guid>("Fk_DanhMucTenQuyen")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("C_Code")
                        .IsUnique();

                    b.HasIndex("Fk_DanhMucTenQuyen");

                    b.ToTable("Tbl_NguoiDung");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5721d0e5-3d84-4add-b584-2fda076e8f12"),
                            C_Avatar = "avatarpath",
                            C_Code = "ACC0001",
                            C_Email = "admin@gmail.com",
                            C_HoVaTen = "Tao La Admin",
                            C_IsDeleted = 2,
                            C_MatKhau = "admin",
                            C_NgayTao = new DateTime(2021, 8, 1, 23, 1, 6, 936, DateTimeKind.Local).AddTicks(821),
                            C_SoDienThoai = "0974084154",
                            C_TrangThai = 2,
                            Fk_DanhMucTenQuyen = new Guid("5ef507d6-48ff-419d-bffa-07291275379e")
                        });
                });

            modelBuilder.Entity("hrmSolution.Data.Entities.Tbl_ChiTietQuyenTheoManHinh", b =>
                {
                    b.HasOne("hrmSolution.Data.Entities.Tbl_DanhMucChucNang", "Tbl_DanhMucChucNang")
                        .WithMany("Tbl_ChiTietQuyenTheoManHinhs")
                        .HasForeignKey("Fk_DanhMucChucNang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hrmSolution.Data.Entities.Tbl_DanhMucManHinh", "Tbl_DanhMucManHinh")
                        .WithMany("Tbl_ChiTietQuyenTheoManHinhs")
                        .HasForeignKey("Fk_DanhMucManHinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hrmSolution.Data.Entities.Tbl_DanhMucTenQuyen", "Tbl_DanhMucTenQuyen")
                        .WithMany("Tbl_ChiTietQuyenTheoManHinhs")
                        .HasForeignKey("Fk_DanhMucTenQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tbl_DanhMucChucNang");

                    b.Navigation("Tbl_DanhMucManHinh");

                    b.Navigation("Tbl_DanhMucTenQuyen");
                });

            modelBuilder.Entity("hrmSolution.Data.Entities.Tbl_NguoiDung", b =>
                {
                    b.HasOne("hrmSolution.Data.Entities.Tbl_DanhMucTenQuyen", "Tbl_DanhMucTenQuyen")
                        .WithMany("Tbl_NguoiDungs")
                        .HasForeignKey("Fk_DanhMucTenQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tbl_DanhMucTenQuyen");
                });

            modelBuilder.Entity("hrmSolution.Data.Entities.Tbl_DanhMucChucNang", b =>
                {
                    b.Navigation("Tbl_ChiTietQuyenTheoManHinhs");
                });

            modelBuilder.Entity("hrmSolution.Data.Entities.Tbl_DanhMucManHinh", b =>
                {
                    b.Navigation("Tbl_ChiTietQuyenTheoManHinhs");
                });

            modelBuilder.Entity("hrmSolution.Data.Entities.Tbl_DanhMucTenQuyen", b =>
                {
                    b.Navigation("Tbl_ChiTietQuyenTheoManHinhs");

                    b.Navigation("Tbl_NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
